# Generated by Django 4.2.6 on 2023-10-31 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='FechaMatricula',
            field=models.DateField(auto_now_add=True),
        ),
    ]
